/* AUTOGENERATED FILE - DO NOT EDIT CONTENTS */

export const projectId = "adpbyfenuvoampozdfzy"
export const publicAnonKey = "eyJhbGciOiJIUzI1NiIsInR5cCI6IkpXVCJ9.eyJpc3MiOiJzdXBhYmFzZSIsInJlZiI6ImFkcGJ5ZmVudXZvYW1wb3pkZnp5Iiwicm9sZSI6ImFub24iLCJpYXQiOjE3NzQzNTk4OTMsImV4cCI6MjA4OTkzNTg5M30.0IYLoPeIdpX-cnX3XpLxFfXopGD9OsJVNUS-w3i8XsA"